package buffon.needle.simulator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Syifa Laili
 */
public class BuffonNeedleSimulator extends javax.swing.JFrame {

    /**
     * Creates new form BuffonNeedleApplication
     */
    public BuffonNeedleSimulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Simulator = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        Description1 = new javax.swing.JLabel();
        labeld1 = new javax.swing.JLabel();
        labeld2 = new javax.swing.JLabel();
        labellength = new javax.swing.JLabel();
        labelnt = new javax.swing.JLabel();
        labelpeluang = new javax.swing.JLabel();
        d1 = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        length = new javax.swing.JTextField();
        nt = new javax.swing.JTextField();
        Enter = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        peluang = new javax.swing.JLabel();
        Kelompok = new javax.swing.JLabel();
        Tommy = new javax.swing.JLabel();
        Syifa = new javax.swing.JLabel();
        Khoirunisa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buffon Needle Simulator");
        setName("Simulator"); // NOI18N

        Simulator.setBackground(new java.awt.Color(0, 0, 153));

        Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Buffon Needle Simulator");

        Description.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Description.setForeground(new java.awt.Color(255, 255, 255));
        Description.setText("To calculate the probability needle touch a line, , where can be obtained from difference");

        Description1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Description1.setForeground(new java.awt.Color(255, 255, 255));
        Description1.setText("Needle touching with a line and total trial");

        javax.swing.GroupLayout SimulatorLayout = new javax.swing.GroupLayout(Simulator);
        Simulator.setLayout(SimulatorLayout);
        SimulatorLayout.setHorizontalGroup(
            SimulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimulatorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(SimulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Description1)
                    .addComponent(Title)
                    .addComponent(Description))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        SimulatorLayout.setVerticalGroup(
            SimulatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimulatorLayout.createSequentialGroup()
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Description1)
                .addContainerGap())
        );

        labeld1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labeld1.setText("d1");

        labeld2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labeld2.setText("d2");

        labellength.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labellength.setText("Panjang Jarum");

        labelnt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelnt.setText("Jumlah Percobaan");

        labelpeluang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelpeluang.setText("Peluang");

        d1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });

        d2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        length.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        nt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntActionPerformed(evt);
            }
        });

        Enter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Enter.setText("Enter");
        Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterActionPerformed(evt);
            }
        });

        Delete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        peluang.setBackground(new java.awt.Color(255, 255, 255));
        peluang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        peluang.setToolTipText("");

        Kelompok.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Kelompok.setText("Nama Anggota Kelompok:");

        Tommy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tommy.setText("1. Tommy Ferdinand S.     06111540000019");

        Syifa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Syifa.setText("2. Syifa Laili Hapsari O.       06111540000035");

        Khoirunisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Khoirunisa.setText("3. Khoirunisa Savira O.       06111540000108");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Simulator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labellength)
                                    .addComponent(labeld2)
                                    .addComponent(labeld1))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(length, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(d1)
                                    .addComponent(d2))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Kelompok)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Syifa)
                                            .addComponent(Tommy)
                                            .addComponent(Khoirunisa)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelpeluang)
                                    .addGap(73, 73, 73)
                                    .addComponent(peluang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelnt)
                                    .addGap(18, 18, 18)
                                    .addComponent(nt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(Enter)
                        .addGap(61, 61, 61)
                        .addComponent(Delete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Simulator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeld1)
                    .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kelompok))
                .addGap(4, 4, 4)
                .addComponent(Tommy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeld2)
                    .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Syifa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Khoirunisa)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labellength)
                    .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnt)
                    .addComponent(nt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(peluang, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelpeluang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enter)
                    .addComponent(Delete))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ntActionPerformed

    private void EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterActionPerformed
        // TODO add your handling code here:
        double valued1 = Double.parseDouble(d1.getText());
        double valued2 = Double.parseDouble(d2.getText());
        double valuelength = Double.parseDouble(length.getText());
        double valuent = Double.parseDouble(nt.getText());
        double ni = 0;
        for(double i = 1; i < valuent; i++) {
            double r1 = Math.random();
            double r2 = Math.random();
            double x = Math.random();
            double a;
            double teta;
            if(x <= valued1/valued1+valued2) {
		a = r1 * valued1/2;
		teta = r2 * Math.PI;
            }
            else {
		a = r1 * valued2/2;
		teta = r2 * Math.PI;
            }
			
            if(a <= valuelength/2 * Math.sin(teta)) {
		ni = ni + 1;
            }
        }
        peluang.setText(String.valueOf(ni/valuent));
    }//GEN-LAST:event_EnterActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d1ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        d1.setText("");
        d2.setText("");
        nt.setText("");
        length.setText("");
        peluang.setText("");
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuffonNeedleSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuffonNeedleSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuffonNeedleSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuffonNeedleSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuffonNeedleSimulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Description1;
    private javax.swing.JButton Enter;
    private javax.swing.JLabel Kelompok;
    private javax.swing.JLabel Khoirunisa;
    private javax.swing.JPanel Simulator;
    private javax.swing.JLabel Syifa;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Tommy;
    public javax.swing.JTextField d1;
    public javax.swing.JTextField d2;
    private javax.swing.JLabel labeld1;
    private javax.swing.JLabel labeld2;
    private javax.swing.JLabel labellength;
    private javax.swing.JLabel labelnt;
    private javax.swing.JLabel labelpeluang;
    public javax.swing.JTextField length;
    public javax.swing.JTextField nt;
    private javax.swing.JLabel peluang;
    // End of variables declaration//GEN-END:variables
}
